spring.application.name=ulajdbc
server.port=8080

# OracleSQL
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=bamboUlaJdbc
spring.datasource.password=bamboUlaJdbc
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver



spring.sql.init.mode=always
